# fly.toml app configuration file generated for sate-pejabat-webprog on 2023-12-19T08:00:33+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "sate-pejabat-webprog"
primary_region = "sin"
console_command = "php /var/www/html/artisan tinker"

[build]
  [build.args]
    NODE_VERSION = "18"
    PHP_VERSION = "8.1"

[deploy]
  release_command = "php /var/www/html/artisan migrate:fresh --force --seed"

[env]
  APP_NAME = "Sate Pejabat"
  APP_ENV = "production"
  LOG_CHANNEL = "stderr"
  LOG_LEVEL = "info"
  LOG_STDERR_FORMATTER = "Monolog\\Formatter\\JsonFormatter"
  SESSION_DRIVER = "cookie"
  SESSION_SECURE_COOKIE = "true"
  APP_URL = "satepejabat.demo.sanii.my.id"
  DB_CONNECTION="mysql"
  DB_HOST="aws.connect.psdb.cloud"
  DB_PORT=3306
  DB_DATABASE="sate"
  MYSQL_ATTR_SSL_CA="/etc/ssl/certs/ca-certificates.crt"

[http_service]
internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[mounts]
  source="sate"
  destination="/var/www/html/storage"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512
